name: Compilar y desplegar

on: # condiciones de ejecucion
  workflow_dispatch: # ejecucion manual
  push:
    branches: # cambio a ramas
      - main
    paths: # cambio en directorios
      - 'BibliotecaAPI/**' # doble asterisco = todo
      - 'BibliotecaAPITests/**'
      - '.github/workflows/compilar-y-desplegar.yml'

env: # variable de entorno a nivel global del archivo
  VERSION_DOTNET: '10.0'

jobs: # 1 job = conjunto de tareas
  build: # nombre de la tarea
    runs-on: ubuntu-latest # ambiente donde se ejecuta esta job
    env: # variable de entorno a nivel del job
      proyecto: BibliotecaAPI/BibliotecaAPI.csproj
    steps: # Pasos de la tarea
      - name: Checkout # nombre paso
        uses: actions/checkout@v6.0.3 # tarea predefinida que permite descargar el proyecto

      - name: Instalar .NET # tarea predefinida que descarga el framework d .NET
        uses: actions/setup-dotnet@v5.3.0
        with: # paramtros adicionals
          dotnet-version: ${{ env.VERSION_DOTNET }} # version del SDK. Se usa la variable creada a nivel global

      - name: Obteniendo depndencias
        run: dotnet restore # comando que descarga las dependencias del proyecto

      - name: Compilar
        run: dotnet build --no-restore # comando para compilar el proyecto pero sin descargar las dependencias

      - name: Realizar pruebas
        run: dotnet test --no-build # comando para correr pruebas sin compilar el proyecto
